# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LAD Dev Blog
email: levi.dixon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dev Blog dicussing technology, database architecture, cloud architecture, big data processing, programming languages, and anything else technogy related.
  AWS, Hive, Spark, Presto, Hbase, AWS, Athena, Redshift, Parquet, ORC, Data Lake
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: LeviAndrewDixon

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
